apiVersion: apps/v1
kind: Deployment
metadata:
  name: dartserver
spec:
  replicas: 10
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: dartserver
          image: lufemunhoz/first-test-k8s:v1
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
